version: "3.7"
services:

  postgres:
    image: postgres:12-alpine
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: blackstone_development
      POSTGRES_PASSWORD: blackstone_development
      POSTGRES_DB: blackstone_development

  vent:
    image: hyperledger/burrow:0.29.5
    restart: on-failure
    command:
    - vent
    - start
    - --db-adapter
    - postgres
    - --db-url
    - postgres://blackstone_development:blackstone_development@postgres:5432/blackstone_development?sslmode=disable
    - --db-schema
    - data
    - --grpc-addr
    - chain:10997
    - --log-level
    - info
    - --spec
    - /app/sqlsol
    - --abi
    - /app/src/bin
    volumes:
    - .:/app
    depends_on:
    - postgres
    - chain

  chain:
    image: hyperledger/burrow:0.29.5
    ports:
    # GRPC port for most interaction
    - "10997:10997"
    # HTTP status/information port
    - "26658:26658"
    volumes:
    - ./src/tests/chain/burrow.toml:/app/burrow.toml
    - ./src/tests/chain/keys:/app/keys
    - type: tmpfs
      target: /app/.burrow
    working_dir: /app
    command:
    - start

  contracts:
    image: hyperledger/burrow:0.29.5
    volumes:
    - type: bind
      source: ./
      target: /app
    - type: tmpfs
      target: /app/src/bin
    working_dir: /app
    depends_on:
    - chain
    command:
    - deploy
    - --chain=chain:10997
    - --address=${CONTRACTS_DEPLOYMENT_ADDRESS}
    - --jobs=1
    - --timeout=30
    - src/build-test.yaml
    - src/test.yaml
